version: '3'

services:
  ruby:
    build: ./webapp/ruby
    volumes:
      - .:/app
    ports:
      #- 5555:5555
      #- 7000:7000
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=isucon
      - MYSQL_PASS=secret
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./webapp/sql:/docker-entrypoint-initdb.d
      - ./webapp/sql/conf:/etc/mysql/conf.d
      - ./datadir:/var/lib/mysql
    environment:
      #- MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=hogehoge
      - MYSQL_DATABASE=isucari
      - MYSQL_USER=isucon
      - MYSQL_PASS=secret
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
  golang:
    image: golang:1.14.6
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
