version: '3'

services:
  composer:
    image: composer
    command: "composer install"
    volumes:
      - ./webapp/php:/app
  php:
    #image: php:7.2-fpm
    build: ./webapp/php
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=isucon
      - MYSQL_PASS=secret
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./webapp/sql:/docker-entrypoint-initdb.d
      - ./webapp/sql/conf:/etc/mysql/conf.d
      - ./datadir:/var/lib/mysql
    environment:
      #- MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=hogehoge
      - MYSQL_DATABASE=isucari
      - MYSQL_USER=isucon
      - MYSQL_PASS=secret
      - MYSQL_PASSWORD=secret
    ports:
      - 3306:3306
  golang:
    image: golang:1.14.6
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "while sleep 1000; do :; done"
